export const ACTION_SET_FROM = "ACTION_SET_FROM";
export const ACTION_SET_TO = "ACTION_SET_TO";
export const ACTION_SET_IS_CITY_SELECTOR_VISIBLE =
  "ACTION_SET_IS_CITY_SELECTOR_VISIBLE";
export const ACTION_SET_CURRENT_SELECTING_LEFT_CITY =
  "ACTION_SET_CURRENT_SELECTING_LEFT_CITY";
export const ACTION_SET_CITY_DATA = "ACTION_SET_CITY_DATA";
export const ACTION_SET_IS_LOADING_CITY_DATA =
  "ACTION_SET_IS_LOADING_CITY_DATA";
export const ACTION_SET_IS_DATE_SELECTOR_VISIBLE =
  "ACTION_SET_IS_DATE_SELECTOR_VISIBLE";
export const ACTION_SET_DEPART_DATE = "ACTION_SET_DEPART_DATE";
export const ACTION_SET_HIGH_SPEED = "ACTION_SET_HIGH_SPEED";
